name: ${project.name}
version: ${project.version}
author: ShE3py

main: fr.she3py.lalambic.Lalambic
api-version: 1.19

permissions:
  lalambic.brew.mundane:
    default: op
  
  lalambic.splash.mundane:
    default: op
  
  lalambic.linger.mundane:
    default: op
  
  lalambic.brew.thick:
    default: op
  
  lalambic.splash.thick:
    default: op
  
  lalambic.linger.thick:
    default: op
  
  lalambic.brew.awkward:
    default: op
  
  lalambic.splash.awkward:
    default: op
  
  lalambic.linger.awkward:
    default: op
  
  lalambic.brew.night_vision:
    default: op
  
  lalambic.lengthen.night_vision:
    default: op
  
  lalambic.splash.night_vision:
    default: op
  
  lalambic.linger.night_vision:
    default: op
  
  lalambic.brew.invisibility:
    default: op
  
  lalambic.lengthen.invisibility:
    default: op
  
  lalambic.splash.invisibility:
    default: op
  
  lalambic.linger.invisibility:
    default: op
  
  lalambic.brew.jump:
    default: op
  
  lalambic.lengthen.jump:
    default: op
  
  lalambic.strengthen.jump:
    default: op
  
  lalambic.splash.jump:
    default: op
  
  lalambic.linger.jump:
    default: op
  
  lalambic.brew.fire_resistance:
    default: op
  
  lalambic.lengthen.fire_resistance:
    default: op
  
  lalambic.splash.fire_resistance:
    default: op
  
  lalambic.linger.fire_resistance:
    default: op
  
  lalambic.brew.speed:
    default: op
  
  lalambic.lengthen.speed:
    default: op
  
  lalambic.strengthen.speed:
    default: op
  
  lalambic.splash.speed:
    default: op
  
  lalambic.linger.speed:
    default: op
  
  lalambic.brew.slowness:
    default: op
  
  lalambic.lengthen.slowness:
    default: op
  
  lalambic.strengthen.slowness:
    default: op
  
  lalambic.splash.slowness:
    default: op
  
  lalambic.linger.slowness:
    default: op
  
  lalambic.brew.water_breathing:
    default: op
  
  lalambic.lengthen.water_breathing:
    default: op
  
  lalambic.splash.water_breathing:
    default: op
  
  lalambic.linger.water_breathing:
    default: op
  
  lalambic.brew.instant_heal:
    default: op
  
  lalambic.strengthen.instant_heal:
    default: op
  
  lalambic.splash.instant_heal:
    default: op
  
  lalambic.linger.instant_heal:
    default: op
  
  lalambic.brew.instant_damage:
    default: op
  
  lalambic.strengthen.instant_damage:
    default: op
  
  lalambic.splash.instant_damage:
    default: op
  
  lalambic.linger.instant_damage:
    default: op
  
  lalambic.brew.poison:
    default: op
  
  lalambic.lengthen.poison:
    default: op
  
  lalambic.strengthen.poison:
    default: op
  
  lalambic.splash.poison:
    default: op
  
  lalambic.linger.poison:
    default: op
  
  lalambic.brew.regen:
    default: op
  
  lalambic.lengthen.regen:
    default: op
  
  lalambic.strengthen.regen:
    default: op
  
  lalambic.splash.regen:
    default: op
  
  lalambic.linger.regen:
    default: op
  
  lalambic.brew.strength:
    default: op
  
  lalambic.lengthen.strength:
    default: op
  
  lalambic.strengthen.strength:
    default: op
  
  lalambic.splash.strength:
    default: op
  
  lalambic.linger.strength:
    default: op
  
  lalambic.brew.weakness:
    default: op
  
  lalambic.lengthen.weakness:
    default: op
  
  lalambic.splash.weakness:
    default: op
  
  lalambic.linger.weakness:
    default: op
  
  lalambic.brew.turtle_master:
    default: op
  
  lalambic.lengthen.turtle_master:
    default: op
  
  lalambic.strengthen.turtle_master:
    default: op
  
  lalambic.splash.turtle_master:
    default: op
  
  lalambic.linger.turtle_master:
    default: op
  
  lalambic.brew.slow_falling:
    default: op
  
  lalambic.lengthen.slow_falling:
    default: op
  
  lalambic.splash.slow_falling:
    default: op
  
  lalambic.linger.slow_falling:
    default: op
  
  lalambic.brew.*:
    default: op
    children:
      lalambic.brew.mundane: true
      lalambic.brew.thick: true
      lalambic.brew.awkward: true
      lalambic.brew.night_vision: true
      lalambic.brew.invisibility: true
      lalambic.brew.jump: true
      lalambic.brew.fire_resistance: true
      lalambic.brew.speed: true
      lalambic.brew.slowness: true
      lalambic.brew.water_breathing: true
      lalambic.brew.instant_heal: true
      lalambic.brew.instant_damage: true
      lalambic.brew.poison: true
      lalambic.brew.regen: true
      lalambic.brew.strength: true
      lalambic.brew.weakness: true
      lalambic.brew.luck: true
      lalambic.brew.turtle_master: true
      lalambic.brew.slow_falling: true
  
  lalambic.lengthen.*:
    default: op
    children:
      lalambic.lengthen.night_vision: true
      lalambic.lengthen.invisibility: true
      lalambic.lengthen.jump: true
      lalambic.lengthen.fire_resistance: true
      lalambic.lengthen.speed: true
      lalambic.lengthen.slowness: true
      lalambic.lengthen.water_breathing: true
      lalambic.lengthen.poison: true
      lalambic.lengthen.regen: true
      lalambic.lengthen.strength: true
      lalambic.lengthen.weakness: true
      lalambic.lengthen.turtle_master: true
      lalambic.lengthen.slow_falling: true
  
  lalambic.strengthen.*:
    default: op
    children:
      lalambic.strengthen.jump: true
      lalambic.strengthen.speed: true
      lalambic.strengthen.slowness: true
      lalambic.strengthen.instant_heal: true
      lalambic.strengthen.instant_damage: true
      lalambic.strengthen.poison: true
      lalambic.strengthen.regen: true
      lalambic.strengthen.strength: true
      lalambic.strengthen.turtle_master: true
  
  lalambic.splash.*:
    default: op
    children:
      lalambic.splash.mundane: true
      lalambic.splash.thick: true
      lalambic.splash.awkward: true
      lalambic.splash.night_vision: true
      lalambic.splash.invisibility: true
      lalambic.splash.jump: true
      lalambic.splash.fire_resistance: true
      lalambic.splash.speed: true
      lalambic.splash.slowness: true
      lalambic.splash.water_breathing: true
      lalambic.splash.instant_heal: true
      lalambic.splash.instant_damage: true
      lalambic.splash.poison: true
      lalambic.splash.regen: true
      lalambic.splash.strength: true
      lalambic.splash.weakness: true
      lalambic.splash.luck: true
      lalambic.splash.turtle_master: true
      lalambic.splash.slow_falling: true
  
  lalambic.linger.*:
    default: op
    children:
      lalambic.linger.mundane: true
      lalambic.linger.thick: true
      lalambic.linger.awkward: true
      lalambic.linger.night_vision: true
      lalambic.linger.invisibility: true
      lalambic.linger.jump: true
      lalambic.linger.fire_resistance: true
      lalambic.linger.speed: true
      lalambic.linger.slowness: true
      lalambic.linger.water_breathing: true
      lalambic.linger.instant_heal: true
      lalambic.linger.instant_damage: true
      lalambic.linger.poison: true
      lalambic.linger.regen: true
      lalambic.linger.strength: true
      lalambic.linger.weakness: true
      lalambic.linger.luck: true
      lalambic.linger.turtle_master: true
      lalambic.linger.slow_falling: true
    
    lalambic.*:
      default: op
      children:
        lalambic.brew.*: true
        lalambic.lengthen.*: true
        lalambic.strengthen.*: true
        lalambic.splash.*: true
        lalambic.linger.*: true
